### ISSUE TITLE
Bot Discord Facebook

### ISSUE THREAD

**Issue by ZerooCool** [Enishowk/Bot-Discord#8]
I search a bot discord for facebook, post facebook message to discord.

**Comment by Enishowk** [comment]
I think you should look for how to integrate the facebook API or just with webhook.

**Comment by ZerooCool** [comment]
Now, i use CoreBot, fot post Twitter message to discord.
https://www.visionduweb.eu/wiki/index.php?title=DiscordApp#CoreBot
